pub const AUTOPAUSE_OFF: &str = "🤖 Autopause OFF!";
pub const AUTOPAUSE_ON: &str = "🤖 Autopause ON!";
pub const CLEARED: &str = "🗑️ Cleared!";

pub const DOMAIN_FORM_ALLOWED_TITLE: &str = "Allowed domains";
pub const DOMAIN_FORM_BANNED_TITLE: &str = "Banned domains";
pub const DOMAIN_FORM_ALLOWED_PLACEHOLDER: &str = "Add domains separated by \';\'. If left blank, all (except for banned) are allowed by default.";
pub const DOMAIN_FORM_BANNED_PLACEHOLDER: &str = "Add domains separated by \';\'. If left blank, all (except for allowed) are blocked by default.";
pub const DOMAIN_FORM_TITLE: &str = "Manage sources";

pub const ERROR: &str = "Fatality! Something went wrong ☹️";
pub const FAIL_ALREADY_HERE: &str = "⚠️ I'm already here!";
pub const FAIL_ANOTHER_CHANNEL: &str = "⚠️ I'm already connected to";
pub const FAIL_AUTHOR_DISCONNECTED: &str = "⚠️ You are not connected to";
pub const FAIL_AUTHOR_NOT_FOUND: &str = "⚠️ Could not find you in any voice channel!";
pub const FAIL_LOOP: &str = "⚠️ Failed to toggle loop!";
pub const FAIL_MINUTES_PARSING: &str = "⚠️ Invalid formatting for 'minutes'";
pub const FAIL_NO_SONG_ON_INDEX: &str = "⚠️ There is no queued song on that index!";
pub const FAIL_NO_VOICE_CONNECTION: &str = "⚠️ I'm not connected to any voice channel!";
pub const FAIL_REMOVE_RANGE: &str = "⚠️ `until` needs to be higher than `index`!";
pub const FAIL_SECONDS_PARSING: &str = "⚠️ Invalid formatting for 'seconds'";
pub const FAIL_WRONG_CHANNEL: &str = "⚠️ We are not in the same voice channel!";
pub const FAIL_VOLUME_PARSING: &str = "⚠️ Invalid formatting for 'volume'";
pub const IDLE_ALERT: &str = "I've been idle for a while, so I'll leave for now to save resources.\nFeel free to summon me back any time!";
pub const JOINING: &str = "Joining";
pub const LEAVING: &str = "👋 See you soon!";
pub const LOOP_DISABLED: &str = "🔁 Disabled loop!";
pub const LOOP_ENABLED: &str = "🔁 Enabled loop!";
pub const NOTHING_IS_PLAYING: &str = "🔈 Nothing is playing!";
pub const PAUSED: &str = "⏸️ Paused!";
pub const PLAY_FAILED_BLOCKED_DOMAIN: &str = "**is either not allowed in this server or is not supported!** \n\nTo explicitely allow this domain, ask a moderator to run the `/managesources` command. [Click to see a list of supported sources.](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md)";
pub const PLAY_ALL_FAILED: &str = "⚠️ Cannot fetch playlist via keywords! Try passing this command an URL.";
pub const PLAY_PLAYLIST: &str = "📃 Added playlist to queue!";
pub const PLAY_QUEUE: &str = "📃 Added to queue!";
pub const PLAY_TOP: &str = "📃 Added to top!";
pub const QUEUE_EXPIRED: &str = "In order to save resources, this command has expired.\nPlease feel free to reinvoke it!";
pub const QUEUE_IS_EMPTY: &str = "Queue is empty!";
pub const QUEUE_NO_SONGS: &str = "There's no songs up next!";
pub const QUEUE_NOTHING_IS_PLAYING: &str = "Nothing is playing!";
pub const QUEUE_NOW_PLAYING: &str = "🔊 Now playing";
pub const QUEUE_PAGE_OF: &str = "of";
pub const QUEUE_PAGE: &str = "Page";
pub const QUEUE_UP_NEXT: &str = "⌛ Up next";
pub const REMOVED_QUEUE_MULTIPLE: &str = "❌ Removed multiple tracks from queue!";
pub const REMOVED_QUEUE: &str = "❌ Removed from queue";
pub const RESUMED: &str = "▶️ Resumed!";
pub const SEARCHING: &str = "🔎 Searching...";
pub const SEEKED: &str = "⏩ Seeked current track to";
pub const SHUFFLED_SUCCESS: &str = "🔀 Shuffled successfully!";
pub const SKIP_VOTE_EMOJI: &str = "🗳 ";
pub const SKIP_VOTE_MISSING: &str = "more vote(s) needed to skip!";
pub const SKIP_VOTE_USER: &str = "has voted to skip!";
pub const SKIPPED_ALL: &str = "⏭️ Skipped until infinity!";
pub const SKIPPED_TO: &str = "⏭️ Skipped to";
pub const SKIPPED: &str = "⏭️ Skipped!";
pub const SPOTIFY_AUTH_FAILED: &str = "⚠️ **Could not authenticate with Spotify!**\nDid you forget to provide your Spotify application's client ID and secret?";
pub const SPOTIFY_INVALID_QUERY: &str = "⚠️ **Could not find any tracks with that link!**\nAre you sure that is a valid Spotify URL?";
pub const SPOTIFY_PLAYLIST_FAILED: &str = "⚠️ **Failed to fetch playlist!**\nIt's likely that this playlist is either private or a personalized recommendation playlist generated by Spotify.";
pub const STOPPED: &str = "⏹️ Stopped!";
pub const TRACK_DURATION: &str = "Track duration: ";
pub const TRACK_NOT_FOUND: &str = "⚠️ **Could not play track!**\nYour request yielded no results.";
pub const TRACK_INAPPROPRIATE: &str = "⚠️ **Could not play track!**\nThe video you requested may be inappropriate for some users, so sign-in is required.";
pub const TRACK_TIME_TO_PLAY: &str = "Estimated time until play: ";
pub const VERSION_LATEST: &str = "Find the latest version [here]";
pub const VERSION: &str = "Version";

pub const CHANGE_DAY: [&str; 3] = [
    "You've all done a terrific job! Well... All but one of you. You know who you are. Please report to HR.",
    "I hope you all worked hard, the performance reviews start later this week.",
    "I was asked to make coffee, go to the break room and enjoy. Also, keep an eye on Linda. We think she's been taking the company's sugar packets.",
];
pub const CHANGE_NIGHT: [&str; 3] = [
    "Another late night at the office? We're not getting paid overtime for this.",
    "The boss wants those sentients collated and on his desk in 50 minutes!",
    "I've been asked to inform you that you have 50 minutes to fill this night's quota!",
];
pub const NO_GROUPS: [&str; 3] = [
    "I see how it is. No one ever invites me to company retreats. Why? Because I'm the boss' secretary and I tell him everything? pshh. Fine. I didn't want to go to your party anyways.",
    "The boss says that you've got to fill your quota by the end of the day, why are you still avoiding the work?",
    "Huh. Guess I'm all alone. No one seems to be here to keep me company. It's okay, I guess I'm used to it.",
];
pub const TEN_MINUTE_WARNING: [&str; 3] = [
    "I've been told to inform you all that the quartermaster is no longer filling out requisition requests as you have 10 minutes until night. I've also been told to inform you all that the quartermaster was just fired.",
    "10 minutes until night time! Remember to keep up with your quarterly quota!",
    "I'm going on break. I'll be back in 10 minutes to watch you all start. I've been told to take notes this time.",
];
pub const FIVE_MINUTE_WARNING: [&str; 3] = [
    "I just came back from setting up the break room for the end of your hunts. We're out of coffee filters, but Phil picked up donuts for everyone, except Linda. She's supposed to be on a diet.",
    "I'll be right back, the boss told me to tell him when one of you spent the night underperforming.",
    "Wrap up your Sentient Finance reports, there's only 5 minutes left for editing. The board wasn't happy with the doodles you added to them last time, so maybe keep those out? Or add little fishes to the doodles. That's what I always do.",
];